#!/bin/bash

# 提示信息
echo "GitFastPoint"
echo -e "\n"
# 检查参数是否为 "-p"、"-c" 或 "-l"
if [ "$1" != "-p" ] && [ "$1" != "-c" ] && [ "$1" != "-l" ]; then
  echo "参数说明："
  echo "-p 参数会直接询问commit message并推送到远端(git add . & git commit -m & git push)"
  echo "-c 参数会询问克隆的地址,同时拉取远程仓库到本地(clone)"
  echo "-l 参数会拉取远端内容到本地repo(pull)"
  exit 1
fi

#!/bin/bash

while true; do
  if [ "\$1" == "-p" ]; then
    read -p "请输入commit message: " message
    if [ -z "$message" ]; then
      echo "错误：commit message 不能为空，请重新输入"
    else
      break
    fi
  elif [ "\$1" == "-c" ]; then
    read -p "请输入git地址: " git_url
    if [ -z "$git_url" ]; then
      echo "错误：git地址不能为空，请重新输入"
    else
      break
    fi
  fi
done


# 执行相应的 git 命令
if [ "$1" == "-p" ]; then
  git add .
  git commit -m "$message"
  git push
elif [ "$1" == "-c" ]; then
  git clone $git_url
elif [ "$1" == "-l" ]; then
  git pull
fi

